name: 'Publish Publish Action'
description: 'GitHub action to publish plugin'

inputs:
  client_id:
    description: Account client id
    required: true
  client_key:
    description: Account client key
    required: true
  realm:
    description: Account realm
    required: true
  studio:
    description: Studio name
    required: true
  plugin_path:
    description: Plugin Path
    required: false
    default: '.'    

runs:
  using: "composite"
  steps:
    - name: Setup STK CLI (beta)
      shell: bash
      run: |
        curl \
          --fail \
          --http2-prior-knowledge \
          --location \
          --output /tmp/stk.deb \
          --silent \
          --show-error \
          --tlsv1.3 \
          https://stk.stackspot.com/installer/linux/stk.deb
        sudo dpkg --install /tmp/stk.deb || echo installed
        rm --force /tmp/stk.deb
    - name: Show STK CLI (beta) version
      shell: bash
      run: $HOME/.stk/bin/stk --version
    - name: Login StackSpot
      shell: bash
      run: |
        $HOME/.stk/bin/stk login -id ${{ inputs.client_id }} -key ${{ inputs.client_key }} -r ${{ inputs.realm }}
      env:
        HTTP_ENABLE_DEBUG: true
    - name: Checkout
      uses: actions/checkout@v3
    - name: Publish plugin
      if: ${{ !contains(inputs.studio, 'UNPUBLISH_ACTION_TEST') }}
      shell: bash
      id: provision
      run: |
        cd ${{ inputs.plugin_path }}
        $HOME/.stk/bin/stk publish plugin --studio ${{ inputs.studio }}
    - name: Show Error Log
      shell: bash    
      if: failure()
      run: |
        cat $HOME/.stk/logs/*
