name: 'Publish Publish Action'
description: 'GitHub action to publish plugin'

inputs:
  client_id:
    description: Account client id
    required: true
  client_key:
    description: Account client key
    required: true
  realm:
    description: Account realm
    required: true
  stk_env:
    description: Stk env
    required: true

runs:
  using: "composite"
  steps:
    - name: Download STK
      shell: bash
      run: curl -O https://stk.stackspot.com/installer/linux/stk-beta.deb

    - name: Install STK and create/move env
      env:
        STK_ENV: ${{ inputs.stk_env }}
      shell: bash
      run: |
        sudo dpkg --install stk-beta.deb
        echo $STK_ENV > $HOME/.stk-beta/.env
        mv $HOME/.stk-beta/bin/* /usr/local/bin
        stk-beta upgrade

    - name: Login to StackSpot Account
      env:
        CLIENT_ID: ${{ inputs.client_id }}
        CLIENT_KEY: ${{ inputs.client_key }}
        REALM: ${{ inputs.realm }}
      shell: bash
      run: stk-beta login --client-id $CLIENT_ID --client-key $CLIENT_KEY --realm $REALM

    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: 'plugin'

    - name: Publish plugin
      shell: bash
      run: stk-beta publish plugin --studio test

    - name: Show Log
      if: always()
      shell: bash
      run: |
        cd $HOME/.stk-beta/logs/
        cat logs.log