name: 'Publish Publish Action'
description: 'GitHub action to publish plugin'

inputs:
  client_id:
    description: Account client id
    required: true
  client_key:
    description: Account client key
    required: true
  realm:
    description: Account realm
    required: true
  studio:
    description: Studio name
    required: true

runs:
  using: "composite"
  steps:
    - name: Download STK
      shell: bash
      run: curl -O https://stk.stackspot.com/installer/linux/stk.deb

    - name: Install STK
      shell: bash
      run: |
        sudo dpkg --install stk.deb
        stk upgrade
        stk --version

    - name: Login to StackSpot Account
      env:
        CLIENT_ID: ${{ inputs.client_id }}
        CLIENT_KEY: ${{ inputs.client_key }}
        REALM: ${{ inputs.realm }}
      shell: bash
      run: stk login --client-id $CLIENT_ID --client-key $CLIENT_KEY --realm $REALM

    - name: Publish plugin
      if: ${{ !contains(inputs.studio, 'UNPUBLISH_ACTION_TEST') }}
      shell: bash
      env:
        STUDIO: ${{ inputs.studio }}
      run: stk publish plugin --studio $STUDIO

    - name: Show Log
      if: always()
      shell: bash
      run: |
        cd $HOME/.stk/logs/
        cat logs.log