name: Action test

on:
  push:
    paths:
      - '.github/workflows/action-test.yml'
      - 'action.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Run publish plugin
        uses: stack-spot/publish-plugin-action@main
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          client_key: ${{ secrets.CLIENT_KEY }}
          realm: ${{ secrets.REALM }}
          stk_env: ${{ secrets.STK_ENV }}
          studio: test